100-hours-a-week/20-real-be

appspec.yml, scripts/start.sh, scripts/stop.sh
AWS Codedeploy 배포를 위한 appspec 파일과 쉘 스크립트 작성을 진행하였습니다.
- Closes #17 
1. [appspec.yml 구현]
2. [scripts/start.sh 구현]
3. [scripts/stop.sh 구현]
=> ✨ feat: Yaml, sh files for AWS Codedeploy

src/main/java/com/real/backend/news/domain/News.java, src/main/java/com/real/backend/news/domain/NewsComment.java, src/main/java/com/real/backend/news/domain/NewsLike.java, src/main/java/com/real/backend/news/repository/NewsCommentRepository.java, src/main/java/com/real/backend/news/repository/NewsLikeRepository.java, src/main/java/com/real/backend/news/repository/NewsRepository.java, src/main/java/com/real/backend/notice/domain/Notice.java, src/main/java/com/real/backend/notice/domain/NoticeComment.java, src/main/java/com/real/backend/notice/domain/NoticeFile.java, src/main/java/com/real/backend/notice/domain/NoticeLike.java, src/main/java/com/real/backend/notice/domain/UserNoticeRead.java, src/main/java/com/real/backend/notice/repository/NoticeCommentRepository.java, src/main/java/com/real/backend/notice/repository/NoticeFileRepository.java, src/main/java/com/real/backend/notice/repository/NoticeLikeRepository.java, src/main/java/com/real/backend/notice/repository/NoticeRepository.java, src/main/java/com/real/backend/notice/repository/UserNoticeReadRepository.java, src/main/java/com/real/backend/post/Post.java
mvp 개발에 필요한 entity와 repository 생성
- Resolves #9
post entity, 뉴스, 뉴스 댓글, 뉴스 좋아요, 공지, 공지 좋아요, 공지 댓글, 공지 읽음 여부, 공지 파일의 entity, repository 생성
- [ X ] 코드가 정상적으로 컴파일되는지 확인했습니다.
- [ X ] 모든 테스트가 성공적으로 통과했습니다.
- [ X ] 관련 문서를 업데이트했습니다.
- [ X ] PR이 관련 이슈를 정확히 참조하고 있습니다.
- [ X ] 코드 스타일 가이드라인을 준수했습니다.
- [ X ] 코드 리뷰어를 지정했습니다.
=> Setting: 기본 entity 및 repository 생성

src/main/java/com/real/backend/config/SecurityConfig.java, src/main/java/com/real/backend/security/filter/JwtFilter.java, src/main/java/com/real/backend/test/HealthCheckController.java
백엔드 헬스체크용 API 개발
- Closes #22 
1. SecurityConfig의 filter 우회
2. JWTUtil 클래스 내의 skip URL 등록
3. API 개발
1. Postman 테스트 진행 완료
=> :sparkles: feat: HealthCheck API 개발

build.gradle, src/main/java/com/real/backend/domain/user/service/UserSignupService.java, src/main/java/com/real/backend/util/S3Utils.java
S3 버킷 업로드 로직, 랜덤 이미지 추출 로직을 포함한 유틸 클래스 생성, 이에 필요한 환경변수 submodule에 주입
- Closes #26 
1. S3Utils 클래스 구현
2. UserSignUpService에 메서드 구현
3. Submodule에 AWS Credentials 추가
커스텀 예외가 잘 이해되지 않아서 일단 마음 가는대로 작성했는데, 추후에 수정하시면 될 것 같습니다!
=> ✨ feat: S3Utils, User 서비스 메서드 추가, submodule

src/main/java/com/real/backend/FastAPIService.java, src/main/java/com/real/backend/domain/chatbot/ChatbotController.java, src/main/java/com/real/backend/domain/chatbot/dto/ChatbotRequestDTO.java, src/main/java/com/real/backend/domain/chatbot/dto/ChatbotResponseDTO.java
챗봇 기능 구현
- Resolves #12 
1. 환경변수를 위한 ai_server 설정
2. ai 챗봇 연동 기능 구현
=> ✨ feat: 챗봇 기능 구현

src/main/java/com/real/backend/config/AwsConfig.java, src/main/java/com/real/backend/domain/user/service/UserSignupService.java, src/main/java/com/real/backend/util/S3Utils.java
CloudFront CDN 도입으로 인한 AWS S3 Util 수정
- Closes #36 
1. S3Utils 수정
2. AWSConfig 클래스 생성
1. Unit Test 진행
=> ♻️ refactor: S3Utils

src/main/java/com/real/backend/BackendApplication.java, src/main/java/com/real/backend/domain/news/repository/NewsRepository.java, src/main/java/com/real/backend/domain/news/service/NewsService.java, src/main/java/com/real/backend/domain/notice/controller/NoticeController.java, src/main/java/com/real/backend/domain/notice/service/NoticeService.java, src/main/java/com/real/backend/domain/notice/tmp/NoticeTmpService.java, src/main/java/com/real/backend/domain/user/service/UserSignupService.java, src/main/java/com/real/backend/infra/ai/dto/NoticeSummaryResponseDTO.java, src/main/java/com/real/backend/infra/ai/service/NoticeAiService.java
ai의 ResponseBody 속성 추가로 인한 코드 수정
(isCompleted 속성 추가)
- Resolves #15
1. ai의 ResponseBody 속성 추가로 인한 코드 수정
=> refactor: ai 응답 body 양식 수정

src/main/java/com/real/backend/domain/notice/tmp/NoticeCreateRequestTmpDTO.java, src/main/java/com/real/backend/domain/notice/tmp/NoticeTmpService.java, src/main/java/com/real/backend/global/BaseEntity.java
임시 공지 생성에 날짜 입력 추가
1. 임시 공지 생성에 날짜 입력 추가
=> refactor: 임시 공지 생성에 날짜 입력 추가

src/main/java/com/real/backend/domain/notice/controller/NoticeController.java, src/main/java/com/real/backend/domain/notice/domain/Notice.java, src/main/java/com/real/backend/domain/notice/service/NoticeService.java, src/main/java/com/real/backend/post/Post.java
공지 수정 기능 구현
1. 공지 수정 기능 구현
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> feat: 공지 수정 기능 구현

src/main/java/com/real/backend/domain/notice/controller/NoticeController.java, src/main/java/com/real/backend/domain/notice/domain/Notice.java
공지 삭제 안되던 버그 수정
1. 공지 삭제 안되던 버그 수정
=> fix: 공지 삭제 안되던 버그 수정

src/main/java/com/real/backend/domain/notice/domain/Notice.java, src/main/java/com/real/backend/global/BaseEntity.java
댓글 작성시 createdAt이 Null인 버그 수정
- Resolves #13
1. 댓글 작성시 createdAt이 Null인 버그 수정
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: 댓글 작성시 createdAt이 Null인 버그 수정

src/main/java/com/real/backend/domain/notice/controller/NoticeController.java, src/main/java/com/real/backend/domain/notice/domain/Notice.java, src/main/java/com/real/backend/domain/notice/dto/NoticePasteRequestDTO.java, src/main/java/com/real/backend/domain/notice/service/NoticeFileService.java, src/main/java/com/real/backend/domain/notice/service/NoticeService.java
팀원들의 공지 작성 기능 관련 수정
1. 공지 작성에 인가 부여
2. 공지 생성시 요약 추가
3. s3 업로드하는 메서드 합침
4. 날짜 수정 안되던 버그 수정
1. [테스트 1]
6. [테스트 2]
7. [테스트 3]
=> ♻️ refactor: 개발자 공지 작성 관련 수정

build.gradle, src/main/java/com/real/backend/domain/chatbot/ChatbotController.java, src/main/java/com/real/backend/domain/news/controller/NewsCommentController.java, src/main/java/com/real/backend/domain/news/controller/NewsController.java, src/main/java/com/real/backend/domain/news/dto/NewsCommentRequestDTO.java, src/main/java/com/real/backend/domain/news/dto/NewsCreateRequestDTO.java, src/main/java/com/real/backend/domain/notice/controller/NoticeCommentController.java, src/main/java/com/real/backend/domain/notice/controller/NoticeController.java, src/main/java/com/real/backend/domain/notice/dto/NoticeCommentRequestDTO.java, src/main/java/com/real/backend/domain/notice/dto/NoticeCreateRequestDTO.java, src/main/java/com/real/backend/domain/notice/dto/NoticePasteRequestDTO.java, src/main/java/com/real/backend/exception/GlobalExceptionHandler.java, src/main/java/com/real/backend/infra/ai/dto/ChatbotRequestDTO.java, src/main/java/com/real/backend/infra/ai/dto/NewsAiRequestDTO.java, src/main/java/com/real/backend/infra/ai/dto/NoticeSummaryRequestDTO.java
검증 관련 로직 추가 및 수정
- Resolves #66 
1. RequestDTO의 필요한 부분에 @NotBlank 어노테이션 추가
2. Controller의 RequestDTO에 @Valid 어노테이션 추가
3. 권한이 없는 사용자의 요청에 대한 에러 메시지 전달하는 기능 추가
1. [테스트 1]
5. [테스트 2]
6. [테스트 3]
=> ♻️ refactor: 검증 관련 로직 추가 및 수정

src/main/java/com/real/backend/domain/notice/service/NoticeFileService.java
파일 이름이 저장되지 않던 버그 수정
1. 파일 이름이 저장되지 않던 버그 수정
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> ♻️ fix: 파일 이름이 저장되지 않던 버그 수정

build.gradle, src/main/java/com/real/backend/domain/news/dto/NewsCommentRequestDTO.java, src/main/java/com/real/backend/domain/news/dto/NewsCreateRequestDTO.java, src/main/java/com/real/backend/domain/news/service/NewsCommentService.java, src/main/java/com/real/backend/domain/news/service/NewsService.java, src/main/java/com/real/backend/domain/notice/controller/NoticeCommentController.java, src/main/java/com/real/backend/domain/notice/domain/Notice.java, src/main/java/com/real/backend/domain/notice/dto/NoticeCommentRequestDTO.java, src/main/java/com/real/backend/domain/notice/dto/NoticeCreateRequestDTO.java, src/main/java/com/real/backend/domain/notice/dto/NoticePasteRequestDTO.java, src/main/java/com/real/backend/domain/notice/service/NoticeCommentService.java, src/main/java/com/real/backend/domain/notice/service/NoticeService.java, src/main/java/com/real/backend/exception/GlobalExceptionHandler.java, src/main/java/com/real/backend/global/aop/Sanitizer.java, src/main/java/com/real/backend/global/aop/XssSanitizer.java, src/main/java/com/real/backend/global/aop/XssSanitizerAspect.java, src/main/java/com/real/backend/infra/ai/dto/ChatbotRequestDTO.java, src/main/java/com/real/backend/infra/ai/dto/NewsAiRequestDTO.java
xss 필터링 기능 추가
- Resolves #69 
1. xss 필터링하는 @Sanitizer 어노테이션 기능 추가
2. 댓글 작성 dto에 @Sanitizer
3. 기타 입력 받는 데이터에 @Sanitizer
=> ✨ feat: xss 필터링 기능 추가

src/main/java/com/real/backend/domain/oauth/domain/RefreshToken.java, src/main/java/com/real/backend/domain/oauth/repository/RefreshTokenRepository.java, src/main/java/com/real/backend/domain/oauth/service/AuthService.java, src/main/java/com/real/backend/domain/user/domain/User.java, src/main/java/com/real/backend/infra/ai/dto/ChatbotRequestDTO.java
챗봇에 값이 안들어가던 버그 수정
- Resolves #12 
1. chatbotRequsetDTO에 Data 어노테이션 추가
2. refresh토큰 저장 로직 추가
1. [테스트 1]
3. [테스트 2]
4. [테스트 3]
=> 🐛fix: 챗봇에 값이 안들어가던 버그 수정

src/main/java/com/real/backend/domain/oauth/service/AuthService.java
쿠키 옵션 설정 변경
- Resolves #11 
1. 쿠키 secure 옵션 true로 변경
=> 🐛refactor : secure 옵션 수정

src/main/java/com/real/backend/domain/news/dto/NewsResponseDTO.java
뉴스의 응답 생성 날짜 포맷 변경
- Resolves #80 
1. createdAt 포맷 통일
=> ♻️ refactor: 뉴스의 응답 생성 날짜 포맷 변경

src/main/java/com/real/backend/domain/auth/service/AuthService.java
RefreshAccessToken 메서드에 transactional 어노테이션 추가
- Resolves #59 
1. RefreshAccessToken 메서드에 transactional 어노테이션 추가해서 오류 해결
=> 🐛️ fix: transactional 어노테이션 추가

src/main/java/com/real/backend/util/CookieUtils.java
access token이 담긴 쿠키의 유효기간을 refresh token의 유효기간과 동일하게 설정
access token이 담긴 쿠키의 유효기간을 refresh token의 유효기간과 동일하게 설정
- Resolves #59 
1. 토큰 생성시 MaxAge 설정 변경
=> ♻️️ refactor: access token이 담긴 쿠키의 유효 기간 수정

src/main/java/com/real/backend/config/SecurityConfig.java, src/main/java/com/real/backend/domain/auth/service/AuthService.java, src/main/java/com/real/backend/security/filter/JwtFilter.java
토큰 재발급 기능 구현
- Resolves #59 
1. config 등에 토큰 재발급 하는 요청이 filter를 거치지 않도록 코드 수정
2. refresh 쿠키의 path 설정
=> ✨ feat: 토큰 재발급 기능 구현

src/main/java/com/real/backend/domain/notice/service/NoticeService.java
공지 생성시 날짜 반영 안되는 버그 수정
- Resolves #101 
1. notice build 로직 변경
=> 🐛️fix: 공지 생성시 날짜 반영 안되는 버그 수정

src/main/java/com/real/backend/domain/news/controller/NewsCommentController.java, src/main/java/com/real/backend/domain/news/controller/NewsLikeController.java, src/main/java/com/real/backend/domain/news/domain/NewsLike.java, src/main/java/com/real/backend/domain/news/repository/NewsLikeRepository.java, src/main/java/com/real/backend/domain/news/repository/NewsRepository.java, src/main/java/com/real/backend/domain/news/service/NewsCommentService.java, src/main/java/com/real/backend/domain/news/service/NewsLikeService.java, src/main/java/com/real/backend/domain/news/service/NewsService.java, src/main/java/com/real/backend/domain/notice/controller/NoticeCommentController.java, src/main/java/com/real/backend/domain/notice/controller/NoticeLikeController.java, src/main/java/com/real/backend/domain/notice/domain/NoticeLike.java, src/main/java/com/real/backend/domain/notice/repository/NoticeLikeRepository.java, src/main/java/com/real/backend/domain/notice/repository/NoticeRepository.java, src/main/java/com/real/backend/domain/notice/service/NoticeCommentService.java, src/main/java/com/real/backend/domain/notice/service/NoticeLikeService.java, src/main/java/com/real/backend/domain/notice/service/NoticeService.java, src/main/java/com/real/backend/domain/user/component/UserFinder.java, src/main/java/com/real/backend/domain/user/domain/UserNoticeRead.java, src/main/java/com/real/backend/domain/user/repository/UserNoticeReadRepository.java, src/main/java/com/real/backend/post/Post.java
데이터베이스의 동시성 관련된 문제 수정
- Resolves #118 
1. 뉴스, 공지의 viewCount, likeCount, commentCount의 데이터 무결성이 깨지는 오류 수정
2. 한 사용자가 공지를 동시에 읽었을 때 user_notice_read 레코드가 두 개 생겨서 unique가 깨지는 문제 수정
3. 좋아요 버튼 클릭 시 dead lock이 걸리는 문제 해결
4. 댓글 생성 시 dead lock이 걸리는 문제 해결
=> 🐛fix: 데이터베이스 동시성 문제 해결

src/main/java/com/real/backend/domain/notice/dto/NoticeInfoResponseDTO.java, src/main/java/com/real/backend/domain/notice/service/NoticeService.java
성능 측정을 위해 공지 응답에 totalViewCount 전달
- Resolves #106 
1. 공지 응답에 totalViewCount 전달
2. 공지 생성시 날짜 적용 안되는 버그 수정
=> ♻️ refactor: 공지 응답에 totalViewCount 전달

src/main/java/com/real/backend/domain/news/controller/NewsCommentController.java, src/main/java/com/real/backend/domain/news/dto/NewsStressResponseDTO.java, src/main/java/com/real/backend/domain/news/repository/NewsCommentRepository.java, src/main/java/com/real/backend/domain/news/repository/NewsRepository.java, src/main/java/com/real/backend/domain/news/service/NewsCommentService.java, src/main/java/com/real/backend/domain/news/service/NewsService.java, src/main/java/com/real/backend/domain/notice/controller/NoticeCommentController.java, src/main/java/com/real/backend/domain/notice/dto/NoticeStressResponseDTO.java, src/main/java/com/real/backend/domain/notice/repository/NoticeCommentRepository.java, src/main/java/com/real/backend/domain/notice/repository/NoticeRepository.java, src/main/java/com/real/backend/domain/notice/service/NoticeCommentService.java, src/main/java/com/real/backend/domain/notice/service/NoticeService.java
댓글 삭제 동시성 문제 해결
- Resolves #118 
1. 댓글 삭제 동시성 문제 해결
2. 댓글 생성시 생성된 id 전달
3. 댓글 삭제시 삭제된 id 전달
=> 🐛 fix: 댓글 삭제 동시성 문제 해결

src/main/java/com/real/backend/batch/NewsSyncScheduler.java, src/main/java/com/real/backend/batch/NoticeSyncScheduler.java, src/main/java/com/real/backend/config/RedisConfig.java, src/main/java/com/real/backend/config/SecurityConfig.java, src/main/java/com/real/backend/domain/news/dto/NewsCreateRequestDTO.java, src/main/java/com/real/backend/domain/notice/service/NoticeService.java, src/main/java/com/real/backend/security/Session.java, src/main/java/com/real/backend/security/filter/JwtFilter.java, src/main/java/com/real/backend/test/TokenGenController.java, src/main/java/com/real/backend/test/UserRequestDTO.java
성능 테스트를 위한 회원가입 기능 추가
- Resolves #106 
1. 성능 테스트를 위한 회원가입 기능 추가
2. redis의 데이터를 flush하는 시간 수정
3. notice 생성 api에 필터를 거치도록 수정
4. 뉴스 생성 최대 글자 수 조정
=> ✨ feat: 테스트를 위한 회원가입 기능 추가

src/main/java/com/real/backend/config/SecurityConfig.java, src/main/java/com/real/backend/test/TokenGenController.java, src/main/java/com/real/backend/test/UserRequestDTO.java
성능 테스트를 위해 자체 회원가입, 로그인 api 추가
- Resolves #106 
1. securityConfig에 /login endpoint permitAll 추가
2. 자체 로그인, 회원가입 기능 추가
=> ✨ feat: 성능 테스트를 위해 자체 회원가입, 로그인 api 추가

src/main/resources/application-dev.properties, src/main/resources/application-prod.properties
properties redis 설정
- Resolves #106 
1.  properties에 redis 설정
=> chore: properties redis 설정

src/main/java/com/real/backend/infra/s3/S3Service.java, src/main/java/com/real/backend/util/S3Utils.java
CloudFront URL 빌드 에러 해결, URL 및 Key '/' 파싱
1. CloudFront URL 빌드 presigned 기준이 아닌 key 기준으로 빌드하도록 수정
2. URL과 Key 조합 시 '/' 중첩 문제 해결하기 위해 Private 메서드 구현
=> Test/presigned/from #146

src/main/java/com/real/backend/config/SecurityConfig.java, src/main/java/com/real/backend/domain/user/controller/UserController.java, src/main/java/com/real/backend/domain/user/controller/UserInvitedController.java, src/main/java/com/real/backend/domain/user/controller/UserNoticeController.java, src/main/java/com/real/backend/domain/user/domain/User.java, src/main/java/com/real/backend/domain/user/dto/ChangeUserInfoRequestDTO.java, src/main/java/com/real/backend/domain/user/dto/ChangeUserRoleRequestDTO.java, src/main/java/com/real/backend/domain/user/dto/InvitedUserCreateRequestDTO.java, src/main/java/com/real/backend/domain/user/service/UserInvitedService.java, src/main/java/com/real/backend/domain/user/service/UserNoticeService.java, src/main/java/com/real/backend/domain/user/service/UserService.java, src/main/java/com/real/backend/security/filter/JwtFilter.java, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties
사용자 관련 api 기능 구현
- Resolves #149 
1. 사용자 role 변경하는 기능 추가
2. 초대된 사용자 추가하는 api 추가
3. 초대된 사용자의 이름, 역할을 변경해주는 api 추가
=> ✨feat: 사용자 관련 api 기능 구현

.github/workflows/auto-tagging.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, Dockerfile, scripts/deploy.sh, scripts/entrypoint.sh, scripts/start.sh, scripts/stop.sh
Dockerfile작성 및 Docker 기반 CI/CD 스크립트 작성
1. Dockerfile 작성
2. Entrypoint.sh 작성
3. CI/CD 스크립트 작성
=> :rocket: deploy: Dockerfile and Github Actions Scripts

scripts/entrypoint.sh, src/main/java/com/real/backend/batch/NewsSyncScheduler.java, src/main/java/com/real/backend/domain/news/controller/NewsController.java, src/main/java/com/real/backend/domain/news/service/NewsAiService.java, src/main/java/com/real/backend/domain/news/service/NewsService.java, src/main/java/com/real/backend/domain/wiki/repository/WikiRepository.java, src/main/java/com/real/backend/domain/wiki/service/WikiService.java
뉴스 관련 기준 변경
- Resolves #138
1. 뉴스 시간을 수정
2. 뉴스 삭제 기능 추가
3. 위키 기반 뉴스 생성 기준 변경
=> ♻️ refactor: 뉴스 관련 변경

src/main/java/com/real/backend/infra/redis/WikiRedisService.java, src/main/java/com/real/backend/modules/wiki/domain/Wiki.java, src/main/java/com/real/backend/modules/wiki/dto/WikiListResponseDTO.java, src/main/java/com/real/backend/modules/wiki/service/WikiService.java
[위키 업데이트 날짜가 반영 안되는 버그 수정](https://github.com/100-hours-a-week/20-real-be/commit/4ec7eb38c6e25c976ebe02bf9e57633583e16bb9)
- Resolves #167 
1. 커서 기반으로 위키를 전달할 때 위키 내용을 redis에서 가져옴
2. redis에 없다면 db에서 가져옴
3. flush할 때 updatedAt이 LastModified 적용되지 않도록 함
=> 🐛 bug: 위키 업데이트 날짜가 반영 안되는 버그 수정

src/main/java/com/real/backend/batch/WikiSyncScheduler.java, src/main/java/com/real/backend/modules/wiki/controller/WikiController.java, src/main/java/com/real/backend/modules/wiki/service/WikiSyncService.java
위키 업데이트 정렬이 안되는 문제 수정
- Resolves #169 
1. 매 조회마다 db에 flush하도록 변경 -> 추후 로직 변경 예정
=> 🐛 fix: 위키 업데이트 정렬이 안되는 문제 수정

src/main/java/com/real/backend/security/JwtUtils.java
토큰 관련 log 삭제
- Resolves #138 
1. 토큰 만료 및 없을 때 보여주는 로그 삭제
=> ♻️ refactor: 토큰 관련 log 삭제

src/main/java/com/real/backend/infra/redis/WikiRedisService.java, src/main/java/com/real/backend/modules/wiki/repository/WikiRepository.java
삭제된 위키는 redis에 업로드 하지 않도록 수정
- Resolves #179 
1. redis로 데이터를 올릴 때 deleted is null만 업로드
=> 🐛 fix: 삭제된 위키가 Redis에 업로드되는 버그 수정

src/main/java/com/real/backend/batch/NewsSyncScheduler.java, src/main/java/com/real/backend/modules/news/controller/NewsController.java, src/main/java/com/real/backend/modules/news/service/NewsAiService.java
wikiId로 뉴스를 생성하는 api 추가
- Resolves #175 
1. wikiId로 뉴스를 생성하는 api 추가
2. 뉴스 생성 메서드 분리
=> ✨ feat: wikiId로 뉴스를 생성하는 api 추가

src/main/java/com/real/backend/modules/auth/controller/AuthController.java, src/main/java/com/real/backend/modules/auth/service/AuthService.java, src/main/java/com/real/backend/modules/auth/service/KakaoService.java, src/main/java/com/real/backend/modules/auth/util/KakaoUtil.java, src/main/java/com/real/backend/modules/user/service/UserInvitedService.java
user, auth service 리팩토링
- Resolves #161 
1. 카카오 관련 메서드가 user service에 있는 걸 KakaoService로 변경
2. auth/kakao -> auth/util로 패키지명 변경
=> ♻️ refactor: user service 리팩토링

src/main/java/com/real/backend/modules/wiki/service/WikiCursorPaginationService.java
위키 검색에 대소문자 구분 없음
- Resolves #206 
1. keyword와 title을 toLowerCase()로 비교
=> ✨ feat: 위키 검색에 대소문자 구분 없음

build.gradle, src/main/java/com/real/backend/common/aop/XssSanitizer.java, src/main/java/com/real/backend/modules/notice/dto/NoticeCreateRequestDTO.java
글에 이모지가 작성 안되는 버그 수정
- Resolves #213 
1. sanitize 후 HTML 엔티티를 다시 디코딩
=> 🐛 fix: 글에 이모지가 작성 안되는 버그 수정 

build.gradle, src/main/java/com/real/backend/common/aop/XssSanitizer.java, src/main/java/com/real/backend/modules/notice/dto/NoticeCreateRequestDTO.java
글에 이모지가 작성 안되는 버그 수정
- Resolves #213 
1. sanitize 후 HTML 엔티티를 다시 디코딩
=> 🐛 fix: 글에 이모지가 작성 안되는 버그 수정

build.gradle, src/main/java/com/real/backend/common/config/WebConfig.java, src/main/java/com/real/backend/common/interceptor/ApiAccessInterceptor.java, src/main/java/com/real/backend/common/util/ActiveUserMetrics.java
동시접속자수 추적을 위한 커스텀 매트릭 구현
- Closes #219 
1. API 인터셉터 구현
2. 커스텀 매트릭 컨트롤러 구현
=> :sparkles: feat: Custom metrics for Concurrent Users

build.gradle, src/main/java/com/real/backend/common/config/WebConfig.java, src/main/java/com/real/backend/common/interceptor/ApiAccessInterceptor.java, src/main/java/com/real/backend/common/util/ActiveUserMetrics.java
동시접속자수 추적을 위한 커스텀 매트릭 구현
- Closes #219 
1. API 인터셉터 구현
2. 커스텀 매트릭 컨트롤러 구현
=> Hotfix/custom metric/219

src/main/java/com/real/backend/common/interceptor/ApiAccessInterceptor.java
=> :ambulance: !hotfix: Interceptor Handler

.gitignore, src/main/java/com/real/backend/BackendApplication.java, src/main/java/com/real/backend/common/config/JpaAuditingConfig.java, src/main/java/com/real/backend/common/exception/GlobalExceptionHandler.java, src/main/java/com/real/backend/modules/user/controller/UserController.java, src/main/java/com/real/backend/modules/user/controller/UserInvitedController.java, src/main/java/com/real/backend/modules/user/controller/UserNoticeController.java, src/main/java/com/real/backend/modules/user/domain/User.java, src/main/java/com/real/backend/modules/user/dto/ChangeUserInfoRequestDTO.java, src/main/java/com/real/backend/modules/user/dto/ChangeUserRoleRequestDTO.java, src/main/java/com/real/backend/modules/user/dto/InvitedUserCreateRequestDTO.java, src/test/java/com/real/backend/config/SecurityTestConfig.java, src/test/java/com/real/backend/modules/user/controller/UserControllerTest.java, src/test/java/com/real/backend/modules/user/controller/UserInvitedControllerTest.java, src/test/java/com/real/backend/modules/user/controller/UserNoticeControllerTest.java, src/test/java/com/real/backend/modules/user/service/UserChangeInfoTest.java, src/test/java/com/real/backend/modules/user/service/UserInvitedServiceTest.java, src/test/java/com/real/backend/modules/user/service/UserNoticeServiceTest.java, src/test/java/com/real/backend/util/MockUserFactory.java, src/test/java/com/real/backend/util/WithMockUser.java, src/test/resources/application-dev.properties, src/test/resources/application-prod.properties
사용자 도메인 테스트코드 작성 및 테스트에 필요한 부분 코드 리팩터링
- Resolves #165 
1. 유저 도메인 테스트코드 작성
2. JpaAuditing config로 분리
3. valid 추가
=> ✅ test: 사용자 도메인 테스트코드 작성

src/main/java/com/real/backend/common/exception/GlobalExceptionHandler.java, src/main/java/com/real/backend/infra/redis/WikiRedisService.java, src/main/java/com/real/backend/modules/wiki/component/WikiFinder.java, src/main/java/com/real/backend/modules/wiki/controller/WikiController.java, src/main/java/com/real/backend/modules/wiki/dto/WikiEditV2RequestDTO.java, src/main/java/com/real/backend/modules/wiki/dto/WikiInfoRequestDTO.java, src/main/java/com/real/backend/modules/wiki/service/WikiService.java
웹소켓 고도화 관련 위키 api 추가 및 수정
- Resolves #234 
1. 위키 아이디로 상세 조회하는 api 구현
2. 위키 수정 v2 구현
i. api키를 이용하여 요청 확인
ii. 편집자 목록 기능 추가
3. 401, 403 예외 핸들링 추가
=> ✨ feat: 웹소켓 고도화 관련 위키 api 추가 및 수정

src/main/java/com/real/backend/common/interceptor/ApiAccessInterceptor.java
interceptor 오탈자 수정
- Resolves #237 
1. interceptor의 uri가 startswith api/vi/news로 되어있던 오탈자를 api/v1/news로 수정
=> 🐛fix: interceptor 오탈자 수정

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
=> 🚑 !HOTFIX: divide codedeploy name

src/main/java/com/real/backend/common/config/SecurityConfig.java, src/main/java/com/real/backend/common/interceptor/ApiAccessInterceptor.java, src/main/java/com/real/backend/modules/user/controller/UserController.java, src/main/java/com/real/backend/modules/user/dto/LoginResponseDTO.java, src/main/java/com/real/backend/modules/wiki/controller/WikiController.java, src/test/java/com/real/backend/modules/user/controller/UserControllerTest.java
위키 관련 endpoint 수정
- Resolves #234 
1. security, filter, interceptor에 node와 통신하는 endpoint 수정
2. 사용자 정보 전달에 id도 전달
=> ♻️ refactor: 위키 관련 endpoint 수정

src/main/java/com/real/backend/infra/redis/WikiRedisService.java
편집중인 사용자의 아이디 목록을 순서대로 쌓는 기능 추가
- Resolves #234 
1. 편집중인 사용자의 아이디 목록을 순서대로 쌓는 기능 추가
=> ✨ feat: 편집중인 사용자의 아이디 목록을 순서대로 쌓는 기능 추가

.github/workflows/deploy-prod.yml
=> setting: cd 파일 수정

src/main/java/com/real/backend/common/interceptor/ApiAccessInterceptor.java, src/main/java/com/real/backend/common/util/CONSTANT.java, src/main/java/com/real/backend/common/util/CookieUtils.java, src/main/java/com/real/backend/modules/auth/controller/AuthController.java, src/main/java/com/real/backend/security/filter/JwtFilter.java, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties
기존의 쿠키가 남아있어서 로그인이 안되는 버그 수정
- Resolves #256 
1. 쿠키 이름 변경
=> 🚑hotfix: 로그인이 안되는 버그 수정

src/main/java/com/real/backend/modules/wiki/domain/Wiki.java
위키 수정한 사람 이름 최대 길이 수정
- Resolves #263 
1. 위키 수정한 사람 이름 최대 길이 수정
=> 🐛fix: 위키 수정한 사람 이름 최대 길이 수정

src/main/java/com/real/backend/modules/wiki/service/WikiCursorPaginationService.java
위키 검색이 안되는 버그 수정
- Resolves #267 
1. split을 뒤에서 처음 나오는 콜론으로 해서 아이디를 가져오도록 수정
=> 🐛fix: 위키 검색이 안되는 버그 수정

src/main/resources/application-dev.properties
AWS Parameter Store 연동을 위한 application-dev.properties 설정을 추가했습니다.
=> EKS 관련 설정 추가

build.gradle, src/main/resources/application-dev.properties
fix: properties, build.gradle 수정
- Resolves #[이슈 번호]
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: properties, build.gradle 수정

build.gradle
- Resolves #[이슈 번호]
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> fix: implementation 버전 추가

src/main/java/com/real/backend/infra/ai/service/AiResponseService.java, src/main/java/com/real/backend/modules/chatbot/controller/ChatbotController.java, src/main/java/com/real/backend/modules/chatbot/service/ChatbotService.java
ai 요청에 apiKey 전송 로직 추가
- Resolves #286 
1. ai 서버에 요청보낼 때 헤더에 api key를 전송하는 로직 추가
2. 필요 없어진 과거 버전의 메서드들 삭제
=> ✨ feat: ai 요청에 apiKey 전송 로직 추가

src/main/java/com/real/backend/common/exception/GlobalExceptionHandler.java, src/main/java/com/real/backend/common/interceptor/ApiAccessInterceptor.java, src/main/java/com/real/backend/infra/sse/repository/SseEmitterRepository.java, src/main/java/com/real/backend/modules/notice/controller/NoticeController.java, src/main/java/com/real/backend/modules/notice/service/NoticeService.java, src/main/java/com/real/backend/modules/notification/controller/NotificationSseController.java, src/main/java/com/real/backend/modules/notification/dto/NoticeCreatedEvent.java, src/main/java/com/real/backend/modules/notification/dto/NotificationEventDTO.java, src/main/java/com/real/backend/modules/notification/handler/NotificationHandler.java, src/main/java/com/real/backend/modules/notification/service/NotificationService.java, src/main/java/com/real/backend/modules/notification/service/NotificationSseService.java
sse 코드리뷰 반영
- Resolves #246 
1. timeOut 에러 메시지 수정
2. timeout시 complete()로 정리
3. interceptor가 모든 비동기 처리를 skip하지 않고, notification만 skip 처리
4. controller, service 역할 분리
5. 클래스 명 수정
6. 연결 전에 sse가 이미 있는 유저의 sse는 정리하고 연결
=> ♻️ refactor: sse 코드리뷰 후 수정

build.gradle, src/main/java/com/real/backend/infra/sse/service/SseEmitterService.java, src/main/java/com/real/backend/modules/auth/controller/AuthController.java, src/main/java/com/real/backend/modules/notification/service/NotificationRecoveryService.java, src/main/java/com/real/backend/modules/notification/service/NotificationSseService.java
SSE transactional로 인한 db connection pool 누수 문제
- Resolves #295 
1. connect 함수에 Transactional 어노테이션 제거
2. db접근하는 유실 데이터 알림 전송 함수는 class를 분리
SSE를 연결하는 함수에서 Transactional 어노테이션이 붙어있어서 connection pool 누수가 발생한 것 같아서 수정합니다.
=> 🐛fix: db connection pool 누수 문제 해결

src/main/java/com/real/backend/modules/notification/service/NotificationSseService.java, src/main/java/com/real/backend/modules/user/repository/UserRepository.java
DB 조회와 네트워크 전송의 분리
- Resolves #295 
1. sendNoticeNotification 메소드 내부에서 DB 조회와 네트워크 전송을 분리
=> 🐛fix: DB 조회와 네트워크 전송의 완벽한 분리

src/main/java/com/real/backend/modules/notice/repository/NoticeRepository.java, src/main/java/com/real/backend/modules/notification/service/NotificationRecoveryService.java, src/main/java/com/real/backend/modules/notification/service/NotificationSseService.java
Connection leak detection warning해결을 위한 코드 수정
- Resolves #295 
1. 유실된 데이터를 전송하지 않도록 코드 수정
=> 🐛 fix: connection leak 문제 해결 시도

src/main/java/com/real/backend/modules/notice/controller/NoticeController.java, src/main/java/com/real/backend/modules/notice/repository/NoticeRepository.java, src/main/java/com/real/backend/modules/notice/service/NoticeCursorPaginationService.java
공지 검색 기능 추가
- Resolves #306 
1. 공지를 키워드로 검색하는 기능 추가
=> ✨ feat: 공지 검색 기능 추가

src/main/java/com/real/backend/infra/redis/NoticeRedisService.java
notice:read:user가 long으로 저장되던 문제 수정
- Resolves #308 
1. loadUserNoticeRead할 때 저장을 String으로 변환하여 저장
=> 🐛fix: notice:read:user가 long으로 저장되던 문제 수정

src/main/java/com/real/backend/infra/redis/NoticeRedisService.java
syncNoticeRead 오탈자 수정
- Resolves #308 
1. 사용자 정보가 없을 때 redis의 key를 제거하는 코드 라인 redisTemplate.delete(keyTemplate+userId);로 수정
=> 🐛fix: syncNoticeRead 오탈자 수정

src/main/java/com/real/backend/modules/notice/repository/NoticeRepository.java
삭제된 공지가 검색되는 버그 수정
- Resolves #314 
1. NoticeRepository의 searchByKeyword 메서드들에 deletedAt is null 조건 추가
=> 🐛fix: 삭제된 공지가 검색되는 버그 수정
